<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html>
  <head>
    <title>bla bla site com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="js/jquery-x.x.x.min.js"></script>
	<script type="text/javascript" src="js/script.js"></script>
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
    <link rel="stylesheet" href="css/style_web.css" type="text/css"/>
  </head>

<body>

<div class="container"> 

<div class="space10"></div>

<!-- menu wrapper -->
<div id="menu-wrapper"> 
<!-- submenu here  -->
<ul>
	<li class="active"><a href="." title="Home"> Home </a></li>
    <?php 
  $array_loop1 = $this->var_array['LOOP_MENU_CAT']; 
 if (is_array($array_loop1)) {

  $array_key1 = key($array_loop1); 
 for ($i1=0; $i1<sizeof($array_loop1[$array_key1]); $i1++){ 
  
  ?> 
 
		<li><a href="cat_<?php  print $array_loop1['ID'][$i1];  ?>
_<?php  print $array_loop1['NAME'][$i1];  ?>
" title="<?php  print $array_loop1['NAME'][$i1];  ?>
"> <?php  print $array_loop1['NAME'][$i1];  ?>
 </a>
		 <ul class="submenu">
		<?php  if ($array_loop1['LOOP_MENU_SUB'][$i1]) {  ?>

			<?php 
  $array_loop2 = $array_loop1['LOOP_MENU_SUB'][$i1]; 
 if (is_array($array_loop2)) {

  $array_key2 = key($array_loop2); 
 for ($i2=0; $i2<sizeof($array_loop2[$array_key2]); $i2++){ 
  
  ?> 
 
				<li><a href="subcat_<?php  print $array_loop2['ID_SUB'][$i2];  ?>
_<?php  print $array_loop2['NAME'][$i2];  ?>
_<?php  print $array_loop2['NAME_SUB_URL'][$i2];  ?>
" 
						title="<?php  print $array_loop2['NAME_SUB'][$i2];  ?>
"> <?php  print $array_loop2['NAME_SUB'][$i2];  ?>
 </a></li>
			<?php    
 } 
 }  ?>

		<?php  }  ?>

		</ul>
		</li>
	<?php    
 } 
 }  ?>

</ul>
<div id="menu-notes"><a style="text-decoration: none; color: #85C2FF;" href="." title="Home">blasite.com</a></div>
<div class="clear"></div>
</div> 
<!-- menu wrapper end -->


<div class="space10"></div>

<table class="tb_main">

<?php  if ($this->var_array['HOME']) {  ?>

<?php  } else {  ?>

<tr>
  <td class="td_title"><a style="text-decoration: none" href="javascript:history.back()">.. <font style="font-size:12px;">Back</font></a></td>
  <td style="vertical-align: bottom;">
    <table align="right" valign="bottom" style="margin-bottom:6px" width="400px">
    <tr>
      <td class="td_menu"></td>
    </tr>
    </table>
  </td>
</tr>
<?php  }  ?>


<tr><td colspan="2" height="12"></td></tr>


<tr>
  <td class="td_red_line" height="400" colspan="2">

<a href="javascript:history.back()">Back</a>
<B>Category: <a href="cat_<?php  print $this->var_array['ID_CAT'];  ?>
_<?php  print $this->var_array['CAT'];  ?>
"><?php  print $this->var_array['CAT'];  ?>
</a>
<BR>Subcategory :  <a href="subcat_<?php  print $this->var_array['ID_SUBCAT'];  ?>
_<?php  print $this->var_array['CAT'];  ?>
_<?php  print $this->var_array['SUBCAT_NAME_URL'];  ?>
"><?php  print $this->var_array['SUBCAT_NAME'];  ?>
</a>
</B>
<BR><BR>

	<div class="title"><?php  print $this->var_array['TITLE'];  ?>
</div>

	<?php  print $this->var_array['DESCRIPTION'];  ?>

	
	</td>
</tr>
	

<tr>
  <td colspan="2" style="text-align:right; padding-top:4px"><span 	
		class="tx_light_grey">Copyright © 20xx bla bla </span></td>
</tr>

<tr><td colspan="2" height="12"></td></tr>

</table>

</div>
</body></html>


		<!-- File generated by classTemplate.php tool. Version 1.22 -->


